"""Export format helpers — PDF and QBO generation for the Reports page."""

import io
import datetime

import pandas as pd
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter, landscape
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle


# ── PDF Export ───────────────────────────────────────────────────────────────

def dataframe_to_pdf(df: pd.DataFrame, title: str, subtitle: str = "") -> bytes:
    """Convert a DataFrame to a formatted PDF report. Returns PDF bytes."""
    buf = io.BytesIO()

    # Use landscape if many columns
    page = landscape(letter) if len(df.columns) > 6 else letter

    doc = SimpleDocTemplate(
        buf,
        pagesize=page,
        leftMargin=0.5 * inch,
        rightMargin=0.5 * inch,
        topMargin=0.5 * inch,
        bottomMargin=0.5 * inch,
    )

    styles = getSampleStyleSheet()
    elements = []

    # Title
    title_style = ParagraphStyle(
        "ReportTitle",
        parent=styles["Heading1"],
        fontSize=16,
        spaceAfter=4,
    )
    elements.append(Paragraph(title, title_style))

    # Subtitle (date range, entity)
    if subtitle:
        sub_style = ParagraphStyle(
            "ReportSubtitle",
            parent=styles["Normal"],
            fontSize=9,
            textColor=colors.grey,
            spaceAfter=12,
        )
        elements.append(Paragraph(subtitle, sub_style))

    elements.append(Spacer(1, 8))

    # Build table data: header row + data rows
    header = list(df.columns)
    data = [header]
    for _, row in df.iterrows():
        data.append([str(v) if pd.notna(v) else "" for v in row])

    # Calculate column widths
    avail_width = page[0] - 1.0 * inch  # page width minus margins
    n_cols = len(header)
    col_width = avail_width / n_cols

    table = Table(data, colWidths=[col_width] * n_cols, repeatRows=1)

    # Style the table
    style_commands = [
        # Header
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1a1a2e")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, 0), 8),
        ("BOTTOMPADDING", (0, 0), (-1, 0), 6),
        ("TOPPADDING", (0, 0), (-1, 0), 6),
        # Body
        ("FONTNAME", (0, 1), (-1, -1), "Helvetica"),
        ("FONTSIZE", (0, 1), (-1, -1), 7.5),
        ("TOPPADDING", (0, 1), (-1, -1), 3),
        ("BOTTOMPADDING", (0, 1), (-1, -1), 3),
        # Grid
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#dddddd")),
        ("LINEBELOW", (0, 0), (-1, 0), 1, colors.HexColor("#1a1a2e")),
        # Alternating rows
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("WORDWRAP", (0, 0), (-1, -1), True),
    ]

    # Alternate row shading
    for i in range(1, len(data)):
        if i % 2 == 0:
            style_commands.append(
                ("BACKGROUND", (0, i), (-1, i), colors.HexColor("#f5f5f5"))
            )

    # Right-align columns that look numeric (Amount, Total, etc.)
    for col_idx, col_name in enumerate(header):
        lower = col_name.lower()
        if any(kw in lower for kw in ["amount", "total", "spending", "income", "net",
                                       "expenses", "avg", "min", "max"]):
            style_commands.append(("ALIGN", (col_idx, 0), (col_idx, -1), "RIGHT"))

    table.setStyle(TableStyle(style_commands))
    elements.append(table)

    # Footer with generation timestamp
    elements.append(Spacer(1, 16))
    footer_style = ParagraphStyle(
        "Footer",
        parent=styles["Normal"],
        fontSize=7,
        textColor=colors.grey,
    )
    now = datetime.datetime.now().strftime("%b %d, %Y at %I:%M %p")
    elements.append(Paragraph(f"Generated by Ledger Oak on {now}", footer_style))

    doc.build(elements)
    return buf.getvalue()


# ── QBO (QuickBooks) Export ──────────────────────────────────────────────────

def transactions_to_qbo(df: pd.DataFrame, entity_key: str,
                         start_date: str, end_date: str) -> str:
    """
    Convert a transactions DataFrame to QBO (OFX/SGML) format.

    Only works with transaction-level data (date, amount, description).
    QBO is the standard import format for QuickBooks Desktop and Online.
    """
    # Format dates as YYYYMMDD
    dt_start = start_date.replace("-", "")
    dt_end = end_date.replace("-", "")
    dt_now = datetime.datetime.now().strftime("%Y%m%d%H%M%S")

    lines = []

    # OFX header (SGML, not XML)
    lines.append("OFXHEADER:100")
    lines.append("DATA:OFXSGML")
    lines.append("VERSION:102")
    lines.append("SECURITY:NONE")
    lines.append("ENCODING:USASCII")
    lines.append("CHARSET:1252")
    lines.append("COMPRESSION:NONE")
    lines.append("OLDFILEUID:NONE")
    lines.append("NEWFILEUID:NONE")
    lines.append("")

    # OFX body
    lines.append("<OFX>")
    lines.append("<SIGNONMSGSRSV1>")
    lines.append("<SONRS>")
    lines.append("<STATUS>")
    lines.append("<CODE>0")
    lines.append("<SEVERITY>INFO")
    lines.append("</STATUS>")
    lines.append(f"<DTSERVER>{dt_now}")
    lines.append("<LANGUAGE>ENG")
    lines.append("</SONRS>")
    lines.append("</SIGNONMSGSRSV1>")

    lines.append("<BANKMSGSRSV1>")
    lines.append("<STMTTRNRS>")
    lines.append("<TRNUID>0")
    lines.append("<STATUS>")
    lines.append("<CODE>0")
    lines.append("<SEVERITY>INFO")
    lines.append("</STATUS>")

    lines.append("<STMTRS>")
    lines.append("<CURDEF>USD")

    lines.append("<BANKACCTFROM>")
    lines.append("<BANKID>000000000")
    lines.append(f"<ACCTID>{entity_key.upper()}")
    lines.append("<ACCTTYPE>CHECKING")
    lines.append("</BANKACCTFROM>")

    lines.append("<BANKTRANLIST>")
    lines.append(f"<DTSTART>{dt_start}")
    lines.append(f"<DTEND>{dt_end}")

    for idx, row in df.iterrows():
        amount = float(row.get("amount", row.get("Amount", 0)))
        date_str = str(row.get("date", row.get("Date", "")))
        date_fmt = date_str.replace("-", "")

        # Description: prefer merchant, fall back to raw description
        merchant = str(row.get("merchant_canonical", row.get("Merchant", "")))
        desc_raw = str(row.get("description_raw", row.get("Description", "")))
        name = merchant if merchant and merchant != "nan" else desc_raw
        name = name[:32]  # QBO name field limit

        category = str(row.get("category", row.get("Category", "")))
        memo = category if category and category != "nan" else ""

        # Transaction type
        trntype = "CREDIT" if amount > 0 else "DEBIT"

        # Unique ID (date + index for uniqueness)
        fitid = f"{date_fmt}{idx:06d}"

        lines.append("<STMTTRN>")
        lines.append(f"<TRNTYPE>{trntype}")
        lines.append(f"<DTPOSTED>{date_fmt}")
        lines.append(f"<TRNAMT>{amount:.2f}")
        lines.append(f"<FITID>{fitid}")
        lines.append(f"<NAME>{name}")
        if memo:
            lines.append(f"<MEMO>{memo}")
        lines.append("</STMTTRN>")

    lines.append("</BANKTRANLIST>")
    lines.append("</STMTRS>")
    lines.append("</STMTTRNRS>")
    lines.append("</BANKMSGSRSV1>")
    lines.append("</OFX>")

    return "\n".join(lines)
